--// ReplicatedStorage.SharedPackages._Index.roblox_roact@1.4.4.roact.createReconcilerCompat.spec (ModuleScript)

return function()
    local v_u_1 = require(script.Parent.createElement)
    local v2 = require(script.Parent.createReconciler)
    local v_u_3 = require(script.Parent.Logging)
    local v4 = require(script.Parent.NoopRenderer)
    local v5 = require(script.Parent.createReconcilerCompat)
    local v_u_6 = v2(v4)
    local v_u_7 = v5(v_u_6)
    it("reify should only warn once per call site", function()
        local v10 = v_u_3.capture(function()
            local v8 = v_u_7.reify(v_u_1("StringValue"))
            v_u_6.unmountVirtualTree(v8)
            local v9 = v_u_7.reify(v_u_1("StringValue"))
            v_u_6.unmountVirtualTree(v9)
        end)
        expect(#v10.warnings).to.equal(1)
        expect(v10.warnings[1]:find("reify")).to.be.ok()
        local v12 = v_u_3.capture(function()
            local v11 = v_u_7.reify(v_u_1("StringValue"))
            v_u_6.unmountVirtualTree(v11)
        end)
        expect(#v12.warnings).to.equal(1)
        expect(v12.warnings[1]:find("reify")).to.be.ok()
    end)
    it("teardown should only warn once per call site", function()
        local v15 = v_u_3.capture(function()
            local v13 = v_u_6.mountVirtualTree(v_u_1("StringValue"))
            v_u_7.teardown(v13)
            local v14 = v_u_6.mountVirtualTree(v_u_1("StringValue"))
            v_u_7.teardown(v14)
        end)
        expect(#v15.warnings).to.equal(1)
        expect(v15.warnings[1]:find("teardown")).to.be.ok()
        local v17 = v_u_3.capture(function()
            local v16 = v_u_6.mountVirtualTree(v_u_1("StringValue"))
            v_u_7.teardown(v16)
        end)
        expect(#v17.warnings).to.equal(1)
        expect(v17.warnings[1]:find("teardown")).to.be.ok()
    end)
    it("update should only warn once per call site", function()
        local v19 = v_u_3.capture(function()
            for _ = 1, 2 do
                local v18 = v_u_6.mountVirtualTree(v_u_1("StringValue"))
                v_u_7.reconcile(v18, v_u_1("StringValue"))
                v_u_6.unmountVirtualTree(v18)
            end
        end)
        expect(#v19.warnings).to.equal(1)
        expect(v19.warnings[1]:find("reconcile")).to.be.ok()
        local v21 = v_u_3.capture(function()
            local v20 = v_u_6.mountVirtualTree(v_u_1("StringValue"))
            v_u_7.reconcile(v20, v_u_1("StringValue"))
            v_u_6.unmountVirtualTree(v20)
        end)
        expect(#v21.warnings).to.equal(1)
        expect(v21.warnings[1]:find("reconcile")).to.be.ok()
    end)
end