--// ReplicatedStorage.SharedPackages._Index.roblox_roact@1.4.4.roact.getDefaultInstanceProperty.spec (ModuleScript)

return function()
    local v_u_1 = require(script.Parent.getDefaultInstanceProperty)
    it("should get default name string values", function()
        local _, v2 = v_u_1("StringValue", "Name")
        expect(v2).to.equal("Value")
    end)
    it("should get default empty string values", function()
        local _, v3 = v_u_1("StringValue", "Value")
        expect(v3).to.equal("")
    end)
    it("should get default number values", function()
        local _, v4 = v_u_1("IntValue", "Value")
        expect(v4).to.equal(0)
    end)
    it("should get nil default values", function()
        local _, v5 = v_u_1("ObjectValue", "Value")
        expect(v5).to.equal(nil)
    end)
    it("should get bool default values", function()
        local _, v6 = v_u_1("BoolValue", "Value")
        expect(v6).to.equal(false)
    end)
end