--// ReplicatedStorage.SharedPackages._Index.roblox_roact@1.4.4.roact.ElementKind.spec (ModuleScript)

return function()
    local v_u_1 = require(script.Parent.Portal)
    local v_u_2 = require(script.Parent.Component)
    local v_u_3 = require(script.Parent.ElementKind)
    describe("of", function()
        it("should return nil for non-table values", function()
            expect(v_u_3.of(nil)).to.equal(nil)
            expect(v_u_3.of(5)).to.equal(nil)
            expect(v_u_3.of(newproxy(true))).to.equal(nil)
        end)
        it("should return nil for table values without an ElementKind key", function()
            expect(v_u_3.of({})).to.equal(nil)
        end)
        it("should return the ElementKind from a table", function()
            local v4 = {
                [v_u_3] = v_u_3.Stateful
            }
            expect(v_u_3.of(v4)).to.equal(v_u_3.Stateful)
        end)
    end)
    describe("fromComponent", function()
        it("should handle host components", function()
            expect(v_u_3.fromComponent("foo")).to.equal(v_u_3.Host)
        end)
        it("should handle function components", function()
            expect(v_u_3.fromComponent(function() end)).to.equal(v_u_3.Function)
        end)
        it("should handle stateful components", function()
            local v5 = v_u_2:extend("Foo")
            expect(v_u_3.fromComponent(v5)).to.equal(v_u_3.Stateful)
        end)
        it("should handle portals", function()
            expect(v_u_3.fromComponent(v_u_1)).to.equal(v_u_3.Portal)
        end)
        it("should return nil for invalid inputs", function()
            expect(v_u_3.fromComponent(5)).to.equal(nil)
            expect(v_u_3.fromComponent(newproxy(true))).to.equal(nil)
        end)
    end)
end