--// ReplicatedStorage.SharedPackages._Index.roblox_roact@1.4.4.roact.Component.spec.extend.spec (ModuleScript)

return function()
    local v_u_1 = require(script.Parent.Parent.Type)
    local v_u_2 = require(script.Parent.Parent.Component)
    it("should be extendable", function()
        local v3 = v_u_2:extend("The Senate")
        expect(v3).to.be.ok()
        expect(v_u_1.of(v3)).to.equal(v_u_1.StatefulComponentClass)
    end)
    it("should prevent extending a user component", function()
        local v_u_4 = v_u_2:extend("Sheev")
        expect(function()
            v_u_4:extend("Frank")
        end).to.throw()
    end)
    it("should use a given name", function()
        local v5 = v_u_2:extend("FooBar")
        local v6 = tostring(v5)
        expect(v6).to.be.a("string")
        expect(v6:find("FooBar")).to.be.ok()
    end)
end