--// ReplicatedStorage.SharedPackages._Index.roblox_roact@1.4.4.roact.Symbol.spec (ModuleScript)

return function()
    local v_u_1 = require(script.Parent.Symbol)
    describe("named", function()
        it("should give an opaque object", function()
            local v2 = v_u_1.named("foo")
            expect(v2).to.be.a("userdata")
        end)
        it("should coerce to the given name", function()
            local v3 = v_u_1.named("foo")
            local v4 = tostring(v3):find("foo")
            expect(v4).to.be.ok()
        end)
        it("should be unique when constructed", function()
            local v5 = v_u_1.named("abc")
            local v6 = v_u_1.named("abc")
            expect(v5).never.to.equal(v6)
        end)
    end)
end