--// ReplicatedStorage.SharedPackages._Index.reselim_flipper@2.0.0.flipper.isMotor.spec (ModuleScript)

return function()
    local v_u_1 = require(script.Parent.isMotor)
    local v2 = require(script.Parent.SingleMotor)
    local v3 = require(script.Parent.GroupMotor)
    local v_u_4 = v2.new(0)
    local v_u_5 = v3.new({})
    it("should properly detect motors", function()
        expect(v_u_1(v_u_4)).to.equal(true)
        expect(v_u_1(v_u_5)).to.equal(true)
    end)
    it("shouldn\'t detect things that aren\'t motors", function()
        expect(v_u_1({})).to.equal(false)
    end)
    it("should return the proper motor type", function()
        local _, v6 = v_u_1(v_u_4)
        local _, v7 = v_u_1(v_u_5)
        expect(v6).to.equal("Single")
        expect(v7).to.equal("Group")
    end)
end